### ISSUE TITLE
documentation for thumbnail images

### ISSUE THREAD

**Issue by russellsamora** [the-pudding/website#203]

**Comment by jadiehm** [comment]
Writing this here, so I can port it wherever it needs to live once the site has been updated:

- Home page story images should be screenshots of the article. These can be straight screenshots, or can be combined from different parts of the article. 
- The primary goal of the screenshot is to give a taste of what is in the article NOT for these images to be completely legible, in fact we'd recommend avoiding any large text in the images, especially headlines. The images should serve as a texture of sorts, elevating and prioritizing the short titles they pair with on the homepage.
- Screenshots can be taken from whatever device (mobile or desktop), but keep in mid that taking the images on desktop will provide you with 2x more room to show off what's in the story since the screen is horizontal and the homepage image is vertical. At desktop, most traditional stories look good at around 800-900px width.
- Keep in mind that our homepage uses a saturated color for the background of the image, so it's good to at least have one color present in your image if possible.
- Homepage images should be sized to 600x700px (WxH) and run through an optimization software like ImageOptim.
- There are no other color or content guidelines you need to follow.
